.\" Authors: Andre Masella
.TH pandaseq-sam 1 "August 2012" "1.0" "USER COMMANDS"
.SH NAME 
pandaseq-sam \- PAired-eND Assembler for DNA sequences from SAM/BAM files
.SH SYNOPSIS
.B pandaseq-sam
.B \-f
.I file.bam
[
.B \-b 
] [
.B \-R
] [
.B \-B
.I barcode
] [
.B \-r
.I orphans.fastq
] ...
.SH DESCRIPTION
PANDASEQ assembles paired-end Illumina reads into sequences, trying to correct for errors and uncalled bases. The assembler reads the sequences in SAM/BAM format with quality information. For more information, see
.BR pandaseq (1).
.SH OPTIONS
All parameters not listed here are identical to their
.BR pandaseq (1)
versions.
.TP
\-b
Input file is in binary (BAM), rather than text (SAM) format.
.TP
\-B code
Replace the barcode stripped during conversion to SAM/BAM. Multiplexed Illumina reads normally contain a barcode to differentiate the sets. These are not present in SAM/BAM files (though are often in the file name). This option allows them to reappear in the names of the sequences output.
.TP
\-f file.sam
The location of the reads in SAM or BAM format. Use \fB-\fR to read from standard input.
.TP
\-R
Normally, the SAM/BAM file holds the reverse read in reverse orientation; that is, it has changed the read such that the orientation of the forward and reverse reads are the same, rather than opposite as they are in FASTQ. This is not universally true. This option causes the reads to be treated like FASTQ reads, in opposite direction, rather than the more typical same orientation. If the reverse primer is not found, it is likely this is the problem.
.TP
\-r orphans.fastq
Writes a FASTQ of all the reads that were rejected by the reader. These were reads that could not be matched to a mate due to either bad SAM flags or the mate being missing from the file. It will also collect any reads that were too long or too short. The SAM flags are printed on the header line in human-readable format.

.SH NOTES
The reverse read is slightly different in SAM/BAM from FASTQ: in FASTQ, the read is stored as it came of the sequencer, while in SAM/BAM, the complement is stored so that the forward and reverse reads in a mate pair are in the same orientation. This is handled properly, but it means that if using \fBsamtools view\fR to pick out the reverse primer, the complement of the reverse primer is displayed instead.

.SH SAM FLAGS
Each SAM sequence is associated with flags that describe the sequence. PANDAseq expects that \fIBAM_FPAIRED\fR to be set on both sequences, \fBBAM_FREVERSE\fR to be set on one of the sequences and \fBBAM_FREAD1\fR to be set on one of the sequences. Normally, \fBBAM_FREVERSE\fR and \fBBAM_FREAD1\fR are set on opposite sequences in a mate pair, but this is not a strict requirement. See
.BR sam (5).

.SH SEE ALSO
.BR pandaseq (1),
.BR pandaxs (1),
.BR samtools (1),
.BR sam (5).
